blank_issues_enabled: false
contact_links:
  - name: Submit a question, idea or discuss with the community
    url: https://github.com/doukutsu-rs/doukutsu-rs/discussions
    about: Get help using doukutsu-rs
  - name: Join the Discord community
    url: https://eslint.org/chat
    about: Talk with the team
