services:
  rust-switch:
    image: ${RUSTSWITCH_IMAGE:-ghcr.io/doukutsu-rs/drshorizon-build-env:1.0.0}
    build:
      context: .

    volumes:
      - ../:/workspace
      - "${CARGO_HOME:-${HOME}/.cargo}/registry:/usr/local/cargo/registry"
      - "${CARGO_HOME:-${HOME}/.cargo}/git:/usr/local/cargo/git"

